services:
  postgres:
    container_name: postgres-sql-booklore
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: booklore
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-booklore
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  booklore-api:
    container_name: booklore-api
    image: booklore/booklore:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
  booklore-ui:
    container_name: booklore-ui
    image: booklore/booklore-ui:1.0.0
    ports:
      - 4200:4200
    networks:
      - spring-demo
    depends_on:
      - booklore-api
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local